"use client";

import { AchievementBadges } from "@/components/growth-timeline/AchievementBadges";
import { GrowthMoments } from "@/components/growth-timeline/GrowthMoments";
import { MilestoneList } from "@/components/growth-timeline/MilestoneList";
import { ProjectEvolution } from "@/components/growth-timeline/ProjectEvolution";
import { SkillProgressionChart } from "@/components/growth-timeline/SkillProgressionChart";
import { TimelineVisualization } from "@/components/growth-timeline/TimelineVisualization";
import { useStudent } from "@/hooks/useStudent";
import type { GrowthTimelineJSON } from "@/lib/ai/generateGrowthTimeline";
import { createClient } from "@/utils/supabase/client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type TimelineRow = { timeline_json: GrowthTimelineJSON };

export function GrowthTimelineClient() {
  const supabase = useMemo(() => createClient(), []);
  const { student, loading: studentLoading, error: studentError } = useStudent();
  const [timeline, setTimeline] = useState<GrowthTimelineJSON | null>(null);
  const [loadingTimeline, setLoadingTimeline] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadTimeline() {
      if (!student?.id) return;
      setLoadingTimeline(true);
      const { data, error: timelineError } = await supabase
        .from("student_growth_timelines")
        .select("timeline_json")
        .eq("student_id", student.id)
        .maybeSingle();
      if (timelineError) setError(timelineError.message);
      setTimeline((data as TimelineRow | null)?.timeline_json ?? null);
      setLoadingTimeline(false);
    }
    void loadTimeline();
  }, [student?.id, supabase]);

  function handleDownload() {
    window.print();
  }

  async function handleShare() {
    if (navigator.share) {
      await navigator.share({ title: "My Educate Cybernetix Growth Timeline", url: window.location.href });
      return;
    }
    await navigator.clipboard.writeText(window.location.href);
    setStatus("Timeline link copied.");
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50 to-violet-50 px-4 py-6 text-slate-950 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl space-y-6">
        <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between print:hidden">
          <div>
            <Link href="/dashboard" className="text-sm font-bold text-cyan-700 hover:text-cyan-900">Dashboard</Link>
            <p className="mt-2 text-sm font-semibold uppercase tracking-wide text-violet-700">
              {student ? `${student.display_name}'s growth timeline` : "Growth timeline"}
            </p>
          </div>
          <div className="flex gap-2">
            <button type="button" onClick={handleDownload} disabled={!timeline} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Download Timeline</button>
            <button type="button" onClick={() => void handleShare()} disabled={!timeline} className="rounded-xl border border-cyan-200 bg-white px-4 py-2 text-sm font-black text-cyan-800 disabled:opacity-50">Share Timeline</button>
          </div>
        </header>

        {(studentError || error) && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 print:hidden">{studentError ?? error}</div>}
        {status && <div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4 text-sm font-semibold text-cyan-800 print:hidden">{status}</div>}

        {studentLoading || loadingTimeline ? (
          <div className="h-96 animate-pulse rounded-2xl bg-white" />
        ) : (
          <div className="space-y-6">
            <TimelineVisualization timeline={timeline} />
            {timeline ? (
              <>
                <MilestoneList milestones={timeline.milestones} />
                <SkillProgressionChart skillProgression={timeline.skill_progression} />
                <ProjectEvolution projectEvolution={timeline.project_evolution} />
                <AchievementBadges achievements={timeline.achievements} />
                <GrowthMoments moments={timeline.growth_moments} />
              </>
            ) : (
              <section className="rounded-2xl border border-white/80 bg-white/90 p-6 text-sm text-slate-600 shadow-sm">
                Growth timelines are generated by an admin after enough student progress data exists.
              </section>
            )}
          </div>
        )}
      </div>
    </main>
  );
}
