"use client";

import { AchievementBadges } from "@/components/certificates/AchievementBadges";
import { CertificateActions } from "@/components/certificates/CertificateActions";
import { CertificatePreview } from "@/components/certificates/CertificatePreview";
import { ProjectSummary } from "@/components/certificates/ProjectSummary";
import { SkillMap } from "@/components/certificates/SkillMap";
import { useProjectProgress } from "@/hooks/useProjectProgress";
import { useStudent } from "@/hooks/useStudent";
import type { CertificateJSON } from "@/lib/ai/generateCertificate";
import { createClient } from "@/utils/supabase/client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type CertificateRow = {
  certificate_json: CertificateJSON;
};

export function CertificatesClient() {
  const supabase = useMemo(() => createClient(), []);
  const { student, loading: studentLoading, error: studentError } = useStudent();
  const { project, loading: projectLoading } = useProjectProgress({ studentId: student?.id ?? null });
  const [certificate, setCertificate] = useState<CertificateJSON | null>(null);
  const [loadingCertificate, setLoadingCertificate] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadCertificate() {
      if (!student?.id) return;
      setLoadingCertificate(true);
      setError(null);

      const query = supabase
        .from("student_certificates")
        .select("certificate_json")
        .eq("student_id", student.id)
        .order("updated_at", { ascending: false })
        .limit(1);

      const { data, error: certificateError } = await query.maybeSingle();
      if (certificateError) setError(certificateError.message);
      setCertificate((data as CertificateRow | null)?.certificate_json ?? null);
      setLoadingCertificate(false);
    }

    void loadCertificate();
  }, [student?.id, supabase]);

  function handleDownload() {
    window.print();
  }

  async function handleShare() {
    const url = window.location.href;
    if (navigator.share) {
      await navigator.share({ title: "Educate Cybernetix Certificate", url });
      return;
    }
    await navigator.clipboard.writeText(url);
    setStatus("Certificate link copied.");
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50 to-violet-50 px-4 py-6 text-slate-950 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl space-y-6">
        <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between print:hidden">
          <div>
            <Link href="/dashboard" className="text-sm font-bold text-cyan-700 hover:text-cyan-900">Dashboard</Link>
            <p className="mt-2 text-sm font-semibold uppercase tracking-wide text-violet-700">
              {student ? `${student.display_name}'s certificate` : "Certificate"}
            </p>
          </div>
          <Link href="/presentation-coach" className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-800 shadow-sm">
            Presentation Coach
          </Link>
        </header>

        {(studentError || error) && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 print:hidden">{studentError ?? error}</div>}
        {status && <div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4 text-sm font-semibold text-cyan-800 print:hidden">{status}</div>}

        {studentLoading || projectLoading || loadingCertificate ? (
          <div className="h-96 animate-pulse rounded-2xl bg-white" />
        ) : (
          <div className="grid gap-6 xl:grid-cols-[1fr_22rem]">
            <div className="space-y-6">
              <CertificatePreview certificate={certificate} studentName={student?.display_name ?? "Student"} />
              <div className="grid gap-6 lg:grid-cols-2 print:grid-cols-1">
                <SkillMap skillMap={certificate?.skill_map ?? null} />
                <ProjectSummary summary={certificate?.project_summary ?? null} />
              </div>
              <AchievementBadges badges={certificate?.achievement_badges ?? []} />
            </div>
            <div className="space-y-6">
              <CertificateActions hasCertificate={Boolean(certificate)} onDownload={handleDownload} onShare={handleShare} />
              {!certificate && (
                <section className="rounded-2xl border border-white/80 bg-white/90 p-5 text-sm leading-6 text-slate-600 shadow-sm">
                  Certificates are generated by an admin when a student completes the program and project presentation.
                  {project && <span className="block pt-2 font-semibold text-slate-900">Current project: {project.title}</span>}
                </section>
              )}
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
